backend:
  name: git-gateway
  branch: master
media_folder: static/images
public_folder: /images
collections:
  - name: config
    label: Config
    files:
      - name: config
        label: Config
        file: site-metadata.json
        fields:
          - widget: string
            name: title
            label: Title
            required: true
            hint: Site title
          - widget: string
            name: logo
            label: Logo
            required: true
            hint: Your site name (logo)
  - name: home
    label: Homes
    folder: src/pages/
    create: true
    extension: md
    slug: '{{slug}}'
    fields:
      - widget: string
        name: title
        label: Title
        required: true
        hint: The title of the page.
      - widget: string
        name: description
        label: Description
        required: false
        hint: Baseline of your homepage
      - widget: hidden
        name: template
        label: Template
        required: true
        default: home
      - widget: markdown
        name: body
        label: Content
        required: false
        hint: Page content
    filter:
      field: template
      value: home
  - name: items
    label: Items
    files:
      - name: items
        label: Items
        file: src/data/items.json
        fields:
          - widget: list
            name: item
            label: Item
            required: false
            hint: An item to be placed
            fields:
              - widget: image
                name: image
                label: Item image
                required: true
              - widget: string
                name: title
                label: Title
                required: true
              - widget: string
                name: description
                label: Description
                required: true
              - widget: string
                name: linkUrl
                label: URL
                required: true
              - widget: string
                name: link
                label: Link title
                required: true
